baseURL: https://unruffled-morse-99b9b5.netlify.app/
title: Blog
author: Yin-Ting Chou
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
footnoteReturnLinkContents: ^
theme: harbor
Author:
  name: Yin-Ting Chou
permalinks:
  page: /:filename/
  post: /posts/:filename/
outputs:
  section:
    - JSON
    - HTML
params:
  favicon: favicon.ico
  logo:
    alt: Logo
    height: 50
    url: icon.png
    width: 50
  mainSections: post
  nav:
    - icon: fas fa-user fa-lg
      identifier: about
      name: About
      url: /about/
      weight: 3
    - icon: fas fa-tag fa-lg
      identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - icon: fas fa-search fa-lg
      identifier: search
      name: Search
      url: /search/
      weight: 3
  social:
    - icon: fab fa-github
      name: github
      url: https://github.com/choux130
